# Generated by Django 2.1.4 on 2019-01-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='math',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='wuli',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
